.TH B004 4
.SH NAME
b004 \- INMOS B004/B008 Transputer TRAM Motherboard
.SH DESCRIPTION
The
.B b004
character device driver interfaces to standard Transputer hardware
compatible with the
.B INMOS
motherboards that plugged into the
.B ISA
bus on the
.B IBM PC
and
.B IBM PC AT
computers.
.SH DESCRIPTION
Hardware that interfaces a Transputer, or a network of Transputers, to
a PC, normally implements the interface standard that
.B INMOS
established with their
.B B004
evaluation board, and which they kept using with the later boards,
although they extended the interface along the way.  The
.B B004
has a simple, polled, interface using a handful of I/O ports on the
.B ISA
bus, The I/O port group was at address 0x150.
.PP
The later
.B B008
board was configurable to three different I/O port blocks (0x150,
0x200, or 0x300), three choices of
.B DMA
channels (0, 1, or 3), and either
.B IRQ
3 or
.B IRQ
5.
The B008 board could turn the
.B IBM PC AT
into a parallel supercomputer.
The
.B T800
processor was about ten times as powerful as that machine, you could
fit ten of those on a single
.B B008
board, and you could squeeze four such boards into the
.B AT,
giving you 400 times the power of the host system.
Three of these boards would have their I/O ports,
.B IRQ,
and
.B DMA
all disabled, being instead internally connected as clients of the
first board in the host system.
.PP
The
.B b004
driver handles the communication with a
.B B004
or
.B B008
compatible board, discovers which of the two it's dealing with, and
handles the I/O operations transparently to the client.  It only
allows one client at a time to open the link, and insists on only one
operation at at time being active on the link.  This was normal for
drivers for these devices, and is expected by software using them.
.PP
Additionally, the driver supports a number of \fIioctl\fR calls, to
handle various parameter settings, particularly I/O timeout, and
status inquiries.  For details of these, read
\fI/usr/include/sys/ioc_b004.h\fR
.SH FILES
The special device used is /dev/link0, as this is the name most
existing applications tend to assume.
.SH BUGS
The driver currently insists that the board must be at I/O address
0x150, and, if a B008, use IRQ 5 and DRQ 1.  This is the setup that
tends to fit with semi-modern PCs with an ISA bus, but the driver
could do with an update to make this configurable, either using run
time switches, or by having minor device numbers representing
different combinations of the available options.
.SH "SEE ALSO"
.BR ispy (1),
.BR mtest (1),
.BR iserver (1)
.SH AUTHOR
Tom Ivar Helbekkmo (tih@hamartun.priv.no)
